### ISSUE TITLE
Wordpress-RSS: Description field with broken content

### ISSUE THREAD

**Issue by jbreu** [oxpus/Feed-Reader-32#1]
When I include the following RSS feed from a Wordpress site, I get some ugly results in the created posts. See attached screenshots for settings and resulting post. The extension seems to have trouble with parsing the feed.

https://iftuz.wordpress.com/feed/

![feedformatting](https://cloud.githubusercontent.com/assets/20864561/25587445/651d1872-2ea4-11e7-90f9-1009257bca6e.png)
![result](https://cloud.githubusercontent.com/assets/20864561/25587446/6551691a-2ea4-11e7-9edc-ad4a24b2b45d.png)

**Comment by oxpus** [comment]
This is not an error of the feed reader.
phpBB itself does not format html tags in posts to display them in the right way.
You must first install an extension or bbcodes to enable this.

**Comment by jbreu** [comment]
OK thanks. I do not want to display all this html stuff. A plain text preview would be fine for me. Is there any easy way to filter it out on the extension side? (a trivial hack would be to remove everything starting with the first "<" in the item description)

**Comment by oxpus** [comment]
Try the new class #3

**Comment by oxpus** [comment]
[https://github.com/oxpus/Feed-Reader-32/blob/master/oxpus/feed/helpers/sfnc_class.php%20without%20html](url)

**Comment by jbreu** [comment]
The replacement class seems to work well in the examples I tested. Thanks!

**Comment by oxpus** [comment]
Fine then I'll close this issue.
Thanks for the feedback.
