### ISSUE TITLE
Title sometimes shown with "<t>...</t>"

### ISSUE THREAD

**Issue by jbreu** [oxpus/Feed-Reader-32#2]
The shortcut to the newest post on the forum index page and the page title when the topic is opened both contain a "<t>...</t>" markup. However, in the topics list in a sub forum this is not shown...

![index page](https://cloud.githubusercontent.com/assets/20864561/25587641/397d25bc-2ea5-11e7-9aaa-a3d53235015f.png)
![forum page](https://cloud.githubusercontent.com/assets/20864561/25587643/39846534-2ea5-11e7-9727-1cb99302e2d9.png)
![topic page firefox](https://cloud.githubusercontent.com/assets/20864561/25587642/3983ce44-2ea5-11e7-94f9-a96c52b3d454.png)

**Comment by oxpus** [comment]
Please check if the <t>-tag is part of the rss feed you will read.
phpBB itself can not display html tags in the right way, so you must first enable this within an extension or BBCode.

**Comment by jbreu** [comment]
The title field in the RSS feed im reading says

`<title>Wien: Burschenschaftshaus großflächig beschmutzt</title>`

So the "<t>" tag is not there. Even if it were, why is the "<t>" only there in some cases and not in others?

**Comment by oxpus** [comment]
Sorry, currently no idea.
Possible the new feed class for reading the content without html may help.

**Comment by jbreu** [comment]
I just realized that github stripped the tags from my comments. I hope this is not confusing.
